baseURL = "http://shunkosa.github.io/lightning-flow-recipes-jp/"
languageCode = "ja"
title = "Lightning Flow Recipes"
theme = "cayman-hugo-theme"

[params]
  # Header text, can be markdown
  project_name = "Lightning Flow Recipes"
  project_tagline = "ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã—ã¦ç·¨é›†å¯èƒ½ãª Lightning ãƒ•ãƒ­ãƒ¼ã®ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã§ã™âš¡ï¸ğŸ› "
  header_background_color = "#005fb2"
  header_background_color_secondary = "#1589ee"
  section_headings_color = "#54698d"
  body_link_color = "#0366d6"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1

[markup.goldmark.renderer]
  unsafe = true
