baseURL = "https://shunkosa.github.io/lightning-flow-recipes-jp/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "Salesforce Flow Recipes"
theme = "book"

[languages]
[languages.ja]
  languageName = 'Japanese'
  contentDir = 'content'
  weight = 1

[params]
  # Header text, can be markdown
  project_name = "Salesforce Flow Recipes"
  project_tagline = "ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã—ã¦ç·¨é›†å¯èƒ½ãª Salesforce ãƒ•ãƒ­ãƒ¼ã®ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã§ã™âš¡ï¸ğŸ› "
  BookMenuBundle = '/menu'

[menu]
  [[menu.after]]
  name = "GitHub"
  url = "https://github.com/shunkosa/lightning-flow-recipes-jp/"

[markup.goldmark.renderer]
  unsafe = true
